### ISSUE TITLE
how to use d2sm in other project

### ISSUE THREAD

**Issue by maoqiuerer** [MKFMIKU/d2sm#2]
from d2sm import DeST
dest = DeST("54", args.patch_size, args.patch_size, Q=args.dest_q, K=args.dest_k, mean_shift=True)
dest_loss = dest(self.hr, self.denoised_hr)

I tried use it in itself project, but it shows " Unresolved reference 'self'  ", and it same to in other porject.
I am new to this field and don't know much about it. I would appreciate it if you could answer me.

**Comment by MKFMIKU** [comment]
just call the function as `dest_loss = dest(hr, denoised_hr)` should solve your problem

**Comment by maoqiuerer** [comment]
but after remove it ，it shows  “ Unresolved reference 'hr' ”
